#!/bin/bash
function put_line_to_profile {
    su -c "echo $1 >> /etc/bash.bashrc"
    su -c "echo $1 >> /etc/zshrc"
}


# Instalação dos pacotes gerais
su -c "dnf upgrade -y"
dnf install epel-release -y 
dnf install neovim unzip zip htop iotop wget lynx curl mlocate openssh-server openssh-clients nano git zsh rsync util-linux-user net-tools -y


# Configurando o neovim
unlink /usr/bin/vim
ln -s /usr/bin/nvim /usr/bin/vim
su -c "echo '' >> /usr/share/nvim/sysinit.vim"
su -c "echo 'set mouse=i' >> /usr/share/nvim/sysinit.vim"


# Configuração do BASH
cd /tmp
git clone https://bitbucket.org/kelsoncm/bashscripts.git
mv /tmp/bashscripts/bash* /etc/
chmod a+x /etc/bash_*
mv /tmp/bashscripts/current_branch /usr/bin/
chmod a+x /usr/bin/current_branch
put_line_to_profile ''
put_line_to_profile '. /etc/bash_alias'
put_line_to_profile '. /etc/bash_alias_git'
su -c "rm -rf /tmp/bashscripts"
source ~/.bashrc


# Python 
dnf -y install python3 python3-pip python3-setuptools
ln -s /usr/bin/python3 /usr/bin/python
ln -s /usr/bin/pip3 /usr/bin/pip
pip install virtualenvwrapper
put_line_to_profile ''
put_line_to_profile 'export WORKON_HOME=\$HOME/.virtualenvs'
put_line_to_profile 'export PROJECT_HOME=\$HOME/devel'
put_line_to_profile 'source /usr/local/bin/virtualenvwrapper.sh'

dnf groupinstall -y "Development Tools"
dnf install -y zlib zlib-devel bzip2-devel openssl-devel sqlite-devel readline-devel python3-tkinter -y
curl https://pyenv.run | bash
echo '

# PYENV
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# PYENV Auto-completions. This should be towards the end of the file.
eval "$(pyenv init -)"
' >> ~/.zshrc
pyenv install 3.12 -f


# Install “Oh My ZSH”
chsh -s /bin/zsh
chsh -s /bin/zsh
zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/popstas/zsh-command-time.git ~/.oh-my-zsh/custom/plugins/command-time
sed -i 's/plugins=(git)/plugins=(git virtualenvwrapper zsh-syntax-highlighting zsh-autosuggestions command-time)/g' ~/.zshrc
sed -i 's/robbyrussell/agnoster/g' ~/.zshrc
source ~/.zshrc


# Install “docker e docker compose plugin”
groupadd docker
usermod -aG docker $USER
yum install -y yum-utils
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
systemctl start docker


# Test “docker e docker compose plugin”
docker --version
docker compose version
docker run --rm hello-world
echo "Se lembre de adicionar o Alma ao suporte no Docker Desktop"

echo "Para instalar uma nova versão: pyenv install 3.12 -f"
echo "Para criar um novo venv: pyenv virtualenv 3.12 ava"
echo "Para ativar a venv: pyenv activate ava"
