#!/bin/bash
function put_line_to_profile {
    sudo su -c "echo $1 >> /etc/bash.bashrc"
    sudo su -c "echo $1 >> /etc/zshrc"
}


# Instalação dos pacotes gerais
sudo su -c "dnf upgrade -y"
sudo dnf install epel-release -y 
sudo dnf install sudo neovim unzip zip htop iotop wget lynx curl mlocate openssh-server openssh-clients nano git zsh rsync util-linux-user net-tools -y

::# Configurando o neovim
sudo unlink /usr/bin/vim
sudo ln -s /usr/bin/nvim /usr/bin/vim
sudo su -c "echo '' >> /usr/share/nvim/sysinit.vim"
sudo su -c "echo 'set mouse=i' >> /usr/share/nvim/sysinit.vim"

# Configuração do BASH
cd /tmp
sudo git clone https://bitbucket.org/kelsoncm/bashscripts.git
sudo mv /tmp/bashscripts/bash* /etc/
sudo chmod a+x /etc/bash_*
sudo mv /tmp/bashscripts/current_branch /usr/bin/
sudo chmod a+x /usr/bin/current_branch
put_line_to_profile ''
put_line_to_profile '. /etc/bash_alias'
put_line_to_profile '. /etc/bash_alias_git'
sudo su -c "rm -rf /tmp/bashscripts"
source ~/.bashrc

# Python 3.9
sudo dnf -y install python3 python3-pip python3-setuptools
sudo ln -s /usr/bin/python3 /usr/bin/python
sudo ln -s /usr/bin/pip3 /usr/bin/pip
sudo pip install virtualenvwrapper
put_line_to_profile ''
put_line_to_profile 'export WORKON_HOME=\$HOME/.virtualenvs'
put_line_to_profile 'export PROJECT_HOME=\$HOME/devel'
put_line_to_profile 'source /usr/local/bin/virtualenvwrapper.sh'


# Install “Oh My ZSH”
chsh -s /bin/zsh
sudo chsh -s /bin/zsh
zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/popstas/zsh-command-time.git ~/.oh-my-zsh/custom/plugins/command-time
sed -i 's/plugins=(git)/plugins=(git virtualenvwrapper zsh-syntax-highlighting zsh-autosuggestions command-time)/g' ~/.zshrc
sed -i 's/robbyrussell/agnoster/g' ~/.zshrc
source ~/.zshrc

# Install “docker, docker-compose e docker compose plugin”
sudo groupadd docker
sudo usermod -aG docker $USER
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
sudo systemctl start docker

echo "Se lembre de adicionar o Alma ao suporte no Docker Desktop"

docker --version
docker compose version
docker-compose --version
docker run --rm hello-world
