#!/bin/bash
alias g=git

alias gsumm='git config --list && echo "Count:" && git shortlog -sn'
alias gsummr='git remote -v && git ls-remote origin'
alias gst='git status'
alias gss='git status -s'

alias ga='git add'
alias gap='git add --patch'

alias gb='git branch'
alias gba='git branch -a'
alias gbr='git branch --remote'

alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcm='git commit -v -m'

alias gsta='git stash'
alias gstd='git stash drop'
alias gstp='git stash pop'
alias gsts='git stash show --text'

alias gl='git pull'
alias ggpull='git pull origin $(current_branch)'

alias gp='git push'
alias ggpush='git push origin $(current_branch)'

alias gco='git checkout'
alias gcom='git checkout master'

alias gd='git diff'
alias gdc='git diff --cached'
alias gdt='git difftool'
alias gwc='git whatchanged -p --abbrev-commit --pretty=medium'

alias gm='git merge'
alias gmt='git mergetool --no-prompt'

alias gclean='git reset --hard && git clean -dfx'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'

alias gignore='git update-index --assume-unchanged'
alias gignored='git ls-files -v | grep "^[[:lower:]]"'

alias gr='git remote'
alias grmv='git remote rename'
alias grrm='git remote remove'
alias grset='git remote set-url'
alias grup='git remote update'

#alias grba='git rebase --abort'
#alias grbc='git rebase --continue'
#alias grbi='git rebase -i'
#alias git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
#alias gk='gitk --all --branches'
#alias glg='git log --stat --max-count=10'
#alias glgg='git log --graph --max-count=10'
#alias glgga='git log --graph --decorate --all'
#alias glo='git log --oneline --decorate --color'
#alias globurl='noglob urlglobber '
#alias glog='git log --oneline --decorate --color --graph'
#alias glp=_git_log_prettily
#alias grt='cd $(git rev-parse --show-toplevel || echo ".")'
#alias gsd='git svn dcommit'
#alias gsps='git show --pretty=short --show-signature'
#alias gsr='git svn rebase'
#alias gts='git tag -s'
#alias gunignore='git update-index --no-assume-unchanged'
#alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
#alias gvt='git verify-tag'
#alias gwip='git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m "--wip--"'
#alias 'gc!'='git commit -v --amend'
#alias 'gca!'='git commit -v -a --amend'
#alias gcs='git commit -S'
#alias gcp='git cherry-pick'
#alias gpoat='git push origin --all && git push origin --tags'
#alias ggpnp='git pull origin $(current_branch) && git push origin $(current_branch)'
#alias gg='git gui citool'
#alias gga='git gui citool --amend'
#alias ggpur='git pull --rebase origin $(current_branch)'
#alias gup='git pull --rebase'
