#!/usr/bin/env python
import sys, re

with open(sys.argv[1], 'r') as f:
    content = f.read()

if not re.match('#\d*.*(\[ADD\]|\[DEL\]|\[UPD\]|\[UPG\])', content):
    print "commit-msg: ERROR! The commit message must start with taskid like '#999' and contains '[ADD]' or '[DEL]' or '[UPD]' or [UPG]" 
    sys.exit(1)

