#!/bin/bash
sudo apt-get -y install vim vim-scripts unzip zip p7zip-full htop iotop wget lynx curl locate ssh nano git sudo build-essential software-properties-common python-software-properties
sudo apt-get -y install linux-headers-3.19.0-33

sudo mv bash* /etc/
sudo chmod a+x /etc/bash_*
sudo mv current_branch /usr/bin/
sudo chmod a+x /usr/bin/current_branch
sudo su -c "echo '' >> /etc/bash.bashrc"
sudo su -c "echo . /etc/bash_alias >> /etc/bash.bashrc"
sudo su -c "echo . /etc/bash_alias_git >> /etc/bash.bashrc"
sudo su -c "echo . /etc/bash_prompt >> /etc/bash.bashrc"

sudo su -c "echo '' >> /etc/vim/vimrc"
sudo su -c "echo 'syntax on' >> /etc/vim/vimrc"
sudo su -c "echo 'colorscheme desert' >> /etc/vim/vimrc"

sudo apt-get -y install python python-dev python-pip virtualenvwrapper python-setuptools
sudo apt-get -y install libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libxml2-dev libxslt1-dev libpq-dev libldap2-dev libsasl2-dev libjpeg-dev libfreetype6-dev freetds-dev

